namespace FactorioToolAssistedSpeedrun.Enums
{
    public enum StepType
    {
        Stop,
        Build,
        Craft,
        Speed,
        Pause,
        Save,
        Recipe,
        Limit,
        Filter,
        Rotate,
        Priority,
        Put,
        Take,
        Mine,
        Launch,
        Next,
        Walk,
        Tech,
        Drop,
        PickUp,
        Wait,
        CancelCrafting,
        NeverIdle,
        KeepWalking,
        KeepOnPath,
        KeepCrafting,
        Shoot,
        Equip,
        Throw,
        Enter,
        Drive,
        Send
    }
}