using FactorioToolAssistedSpeedrun.Entities;
using FactorioToolAssistedSpeedrun.Enums;
using FactorioToolAssistedSpeedrun.Models.Database;
using System.IO;
using System.Text;

namespace FactorioToolAssistedSpeedrun.Commands.Features
{
    public static class AddStepsFileCommand
    {
        public static async Task Execute(string folderLocaton, List<Step> steps, List<Building> buildings)
        {
            var filePath = Path.Combine(folderLocaton, "steps.lua");
            await using var writer = new StreamWriter(filePath, false, Encoding.UTF8);

            await writer.WriteLineAsync("-- This file was generated by Factorio Tool Assisted Speedrun");
            await writer.WriteLineAsync("local step = {}");
            await writer.WriteLineAsync();

            foreach (var (item, index) in steps.Where(x => !x.IsSkip).Select((x, index) => (x, index)))
            {
                try
                {
                    await writer.WriteLineAsync(StepFormat(item, index + 1, buildings));
                }
                catch (Exception ex)
                {
                    throw new Exception($"Error processing step at location {item.Location}: {ex.Message}", ex);
                }
            }

            await writer.WriteLineAsync($"step[{steps.Count + 1}] = {{\"break\"}}");
            await writer.WriteLineAsync();
            await writer.WriteLineAsync("return step");
        }

        private static string StepFormat(Step step, int count, List<Building> buildings)
        {
            var sb = new StringBuilder();

            var type = step.Type;
            sb.Append($"step[{count}] = {{{step.Location}");
            if (type == StepType.PickUp)
            {
                sb.Append($", \"pick\"");
            }
            else if (type == StepType.Speed)
            {
                sb.Append($", \"speed\"");
            }
            else
            {
                sb.Append($", \"{StepTypeExtensions.ToString(type)}\"");
            }
            if (type.ContainFlag(ParameterFlag.Point))
            {
                sb.Append($", {{{step.X:F6}, {step.Y:F6}}}");
            }

            if (type == StepType.Craft || type == StepType.CancelCrafting)
            {
                if (type.ContainFlag(ParameterFlag.Amount))
                {
                    if (step.Amount < 1)
                        sb.Append($", -1");
                    else
                        sb.Append($", {step.Amount}");
                }
                if (type.ContainFlag(ParameterFlag.Item))
                {
                    sb.Append($", \"{step.Item}\"");
                }
            }
            else
            {
                if (type.ContainFlag(ParameterFlag.Item))
                {
                    sb.Append($", \"{step.Item}\"");
                }

                if (type.ContainFlag(ParameterFlag.Amount))
                {
                    if (type == StepType.Rotate)
                    {
                        if (step.Amount == 3)
                            sb.Append(", true");
                        else
                            sb.Append(", false");
                    }
                    else
                    {
                        if (step.Amount < 1)
                            sb.Append($", -1");
                        else
                            sb.Append($", {step.Amount}");
                    }
                }
            }

            if (type.ContainFlag(ParameterFlag.Orientation))
            {
                sb.Append($", {step.Orientation!.Value.GetOrientationDefines()}");
            }

            if (type.ContainFlag(ParameterFlag.Inventory))
            {
                sb.Append($", {OrientationInventory(buildings, step.Inventory!.Value, step.Location, step.X, step.Y)}");
            }

            if (type.ContainFlag(ParameterFlag.Priority))
            {
                sb.Append($", {step.Priority!.ToLuaString()}");
            }

            if (type.ContainFlag(ParameterFlag.Modifier) && step.Modifier.HasValue)
            {
                if (step.Type != StepType.Mine)
                {
                    sb.Append($", {ModifierTypeExtensions.ToLuaString(step.Modifier.Value)}");
                }
            }

            if (step.Type == StepType.Filter)
            {
                sb.Append($", {OrientationFilter(buildings, step.Location, step.X, step.Y)}");
            }

            if (step.Type == StepType.Save)
            {
                sb.Append($", \"{step.Comment}\"");
            }
            else
            {
                var comment = string.IsNullOrEmpty(step.Comment) ? "" : $", comment = \"{step.Comment}\"";
                sb.Append($"{comment}");
            }
            sb.Append("}");
            return sb.ToString();
        }

        private static string OrientationInventory(List<Building> buildings, InventoryType inventoryType, int id = 0, double x = 0, double y = 0)
        {
            if (inventoryType == InventoryType.Input || inventoryType == InventoryType.Modules)
            {
                var entity = buildings
                    .Where(b => Math.Abs(b.X - x) < 0.0001 && Math.Abs(b.Y - y) < 0.0001 && b.Location < id)
                    .MaxBy(x => x.Location);
                return inventoryType.GetInventoryDefines(entity?.Name ?? "");
            }

            return inventoryType.GetInventoryDefines();
        }

        private static string OrientationFilter(List<Building> buildings, int id, double x, double y)
        {
            var entity = buildings
                    .Where(b => Math.Abs(b.X - x) < 0.0001 && Math.Abs(b.Y - y) < 0.0001 && b.Location < id)
                    .MaxBy(x => x.Location) ?? throw new Exception($"Cannot find building at ({x}, {y}) for step {id}");

            if (entity.Name.Contains("splitter"))
            {
                return "\"splitter\"";
            }
            else if (entity.Name.Contains("inserter"))
            {
                return "\"inserter\"";
            }
            else
            {
                throw new Exception($"Unknown entity type for filter orientation: {entity.Name}");
            }
        }
    }
}
